name: youtube
version: 0.1
main: me.gameplax.youtube.youtube
author: gameplax
description: youtube
depend: [Vault]
commands:
     kit:
          description: Kits!
          usage: /kit
     lobby:
          description: Zum Lobby Server
          usage: /Lobby
     open:
          description: Oeffnet Enderchest und Enchantment tabel
          usage: /open <ender/chant>